### PR TITLE
Branch

### PR DESCRIPTION
**Pull request by kikunojojou**
I made changes to basic-intersection,cpp
It kept on getting in the way when I was using the program.
If the pull request is all messed up, then I don't know what actually happened

### CODE REVIEW

**Comment by dou10** [comment]
Not sure how to approve this pull request

**Review by dou10 — APPROVED** [review]

**Comment by kyledewey** [comment]
Assigned @AshotC.

I see @dou10 already provided a review.  @dou10: could you still review the other code I assigned you to?  That code still needs a review.  For the sake of fairness, I'll double-count your review for this week (effectively a 1% bonus in the class).

In the future, unless you make prior arrangements with me, please do not assign reviewers yourself.  I'm intentionally moving students around different projects to increase the breadth of the code you're looking at.

**Review by AshotC — APPROVED** [review]
Not much here to review. Your single line change looks fine.

**Comment by kikunojojou** [comment]
The tests don't work when ran as is. They need GNOME to run, and I just put a few comments to state this

**Pull request merged**
