### PR TITLE
Update src/extension/effect.cpp

### PR DESCRIPTION
**Pull request by kikunojojou**
The code was really condensed and hard to read. The comments were after the loops, which felt odd so i put them in the front of the loops or conditionals.  Also if you see a lot of pull requests, it's because I accidentally merged so I did a bit of fancy footwork to revert and put this file in a readable manner

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @dou10

**Comment by kyledewey** [comment]
Additionally assigned @cooljohnny3

**Review by cooljohnny3 — COMMENTED** [review]
Well documented code literally saves lives.  Looks good.

**Review by dou10 — APPROVED** [review]
Clean/ small amount of changes/easy to read

**Pull request merged**
