### PR TITLE
Some cleaning up and adding a SVG randomizer

### PR DESCRIPTION
**Pull request by kikunojojou**
just some clean-ups by turning stuff into comments because I don't completely understand this system

also imported a SVG generator, but need to make a script to have automatically test the data

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @areeba-waheed

**Comment by kyledewey** [comment]
Additionally assigned @cooljohnny3

**Review by areeba-waheed — APPROVED** [review]
Generator.js looks good, easy to follow!! Comments are always helpful.

**Comment by kikunojojou** [comment]
Just cleaning up and reorganizing code

**Pull request closed without merging**
